/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.teste2.mavenproject1;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author niellefranca
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

  @Override
  public Set<Class<?>> getClasses() {
    Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
    addRestResourceClasses(resources);
    return resources;
  }

  /**
   * Do not modify addRestResourceClasses() method.
   * It is automatically re-generated by NetBeans REST support to populate
   * given list with all resources defined in the project.
   */
  private void addRestResourceClasses(Set<Class<?>> resources) {
    resources.add(br.com.teste2.mavenproject1.ProjectResource.class);
  }
  
}
